# Development version with database management tools
services:
  # PostgreSQL database with pgvector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: eu-green-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-eu_green_chatbot}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - eu-green-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: eu-green-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - eu-green-network

  # pgAdmin for PostgreSQL management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: eu-green-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - eu-green-network

  # Redis Commander for Redis management (ARM64 compatible)
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: eu-green-redis-commander
    environment:
      REDIS_HOSTS: redis:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - eu-green-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        BUILDKIT_PROGRESS: plain
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: eu-green-backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/eu_green_chatbot
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY:-}
      - AI_SERVICE_HOST=0.0.0.0
      - AI_SERVICE_PORT=8000
      - CORS_ORIGIN=http://localhost:3000
      # Whisper/Audio processing configuration
      - TEMP_DIR=/tmp/audio
      - MAX_AUDIO_SIZE=26214400  # 25MB in bytes
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./logs:/app/logs
      # Temporary volume for audio file processing
      - /tmp/audio:/tmp/audio
    # Resource limits for audio processing (development)
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.5'
        reservations:
          memory: 512M
          cpus: '0.5'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - eu-green-network

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        BUILDKIT_PROGRESS: plain
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: eu-green-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - eu-green-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  eu-green-network:
    driver: bridge